### PR TITLE
[1.x] Feature withIcon option

### PR DESCRIPTION
**Pull request by muhamedRadwan**
I found there is no way to add icon to notification/message with this amazing package 
for that I tried to help :)

### CODE REVIEW

**Comment by muhamedRadwan** [comment]
@gentritabazi01 any update ?

**Comment by gentritcarbmanager** [comment]
You need to delete `.gitignore` ?

**Comment by gentritabazi01** [comment]
You need to delete .gitignore ?

**Comment by muhamedRadwan** [comment]
I will delete it but I think this decision is wrong

**Comment by muhamedRadwan** [comment]
check @gentritabazi01

**Review by gentritabazi01 — APPROVED** [review]

**Comment by gentritabazi01** [comment]
Thanks @muhamedRadwan for your contributions.

**Pull request merged**
